-- Davao Medical School Foundation, Inc.
-- Admission System Database Schema
-- Version: 1.2 (Updated with full document requirements)

-- 1. Create the Database
CREATE DATABASE IF NOT EXISTS admission_system;
USE admission_system;

-- 2. Create the Admins Table
-- Contains credentials for college-specific admins and the superadmin.
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, -- Store hashed passwords
    email TEXT NULL, -- Email for notifications (comma-separated for multiple)
    college ENUM('Medicine', 'Nursing', 'Dentistry', 'Midwifery', 'Biology', 'All') NOT NULL,
    is_super_admin TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Default Admins (Password for all: password)
-- These will be inserted only if they don't cause a conflict (username is UNIQUE).
INSERT IGNORE INTO admins (username, password, email, college, is_super_admin) VALUES 
('admin_med', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'med_admin@dmsf.edu.ph', 'Medicine', 0),
('admin_nursing', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'nursing_admin@dmsf.edu.ph', 'Nursing', 0),
('admin_dent', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'dent_admin@dmsf.edu.ph', 'Dentistry', 0),
('admin_mid', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'mid_admin@dmsf.edu.ph', 'Midwifery', 0),
('admin_bio', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'bio_admin@dmsf.edu.ph', 'Biology', 0),
('superadmin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'superadmin@dmsf.edu.ph', 'All', 1);

-- 3. Create the Applications Table
-- Stores all data spread across the 5-step application process.
CREATE TABLE IF NOT EXISTS applications (
    -- Internal Tracking
    id INT AUTO_INCREMENT PRIMARY KEY,
    
    -- STEP 1: Basic Information & Initial Scores
    family_name VARCHAR(100) NOT NULL,
    given_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    email VARCHAR(150) NOT NULL,
    college VARCHAR(100) NOT NULL,
    score_type ENUM('NMAT', 'GWA') NOT NULL,
    score_value DECIMAL(5,2),
    gwa_value DECIMAL(5,2),
    nmat_date VARCHAR(50),
    board_rating DECIMAL(5,2),
    mailing_address TEXT,
    mobile_no VARCHAR(20),
    tel_no_mailing VARCHAR(20),
    home_address TEXT,
    tel_no_home VARCHAR(20),
    social_media VARCHAR(255),
    
    -- STEP 2: Personal & Medical Data
    age INT,
    date_of_birth DATE,
    place_of_birth VARCHAR(255),
    sex ENUM('Male', 'Female', 'Other'),
    civil_status VARCHAR(50),
    religion VARCHAR(100),
    citizenship VARCHAR(100),
    height_ft INT,
    height_in INT,
    weight_kilos_initial DECIMAL(5,2),
    weight_kilos_now DECIMAL(5,2),
    medical_history TEXT,
    physical_disability_flag TINYINT(1) DEFAULT 0,
    physical_disability_details TEXT,
    convicted_flag TINYINT(1) DEFAULT 0,
    convicted_explanation TEXT,
    
    -- STEP 3: Family & Financial Background
    father_first_name VARCHAR(100),
    father_middle_name VARCHAR(100),
    father_last_name VARCHAR(100),
    father_age INT,
    father_deceased TINYINT(1) DEFAULT 0,
    mother_first_name VARCHAR(100),
    mother_middle_name VARCHAR(100),
    mother_last_name VARCHAR(100),
    mother_age INT,
    mother_deceased TINYINT(1) DEFAULT 0,
    father_occupation VARCHAR(100),
    mother_occupation VARCHAR(100),
    family_address TEXT,
    family_contact_no VARCHAR(50),
    income_salaries TINYINT(1) DEFAULT 0,
    income_farm TINYINT(1) DEFAULT 0,
    income_commissions TINYINT(1) DEFAULT 0,
    income_rentals TINYINT(1) DEFAULT 0,
    income_pension TINYINT(1) DEFAULT 0,
    income_business TINYINT(1) DEFAULT 0,
    income_others VARCHAR(255),
    total_family_income VARCHAR(100),
    family_assets TEXT,
    parent_dmsf_grad_flag TINYINT(1) DEFAULT 0,
    parent_dmsf_course VARCHAR(100),
    parent_dmsf_year VARCHAR(50),
    parent_dmsf_teaching_flag TINYINT(1) DEFAULT 0,
    parent_dmsf_teaching_years INT,
    num_brothers INT DEFAULT 0,
    num_sisters INT DEFAULT 0,
    brothers_hs INT DEFAULT 0,
    sisters_hs INT DEFAULT 0,
    brothers_college INT DEFAULT 0,
    sisters_college INT DEFAULT 0,
    brothers_courses TEXT,
    sisters_courses TEXT,
    siblings_middle_school INT DEFAULT 0,
    sibling_dmsf_flag TINYINT(1) DEFAULT 0,
    sibling_dmsf_details TEXT,
    
    -- STEP 4: Educational Background & Intent
    primary_school VARCHAR(255),
    primary_location VARCHAR(255),
    primary_dates VARCHAR(100),
    secondary_school VARCHAR(255),
    secondary_location VARCHAR(255),
    secondary_dates VARCHAR(100),
    hs_honors_flag TINYINT(1) DEFAULT 0,
    hs_honor_type VARCHAR(255),
    college_name_address TEXT,
    degree_obtained VARCHAR(255),
    date_of_graduation VARCHAR(50),
    college_honors_flag TINYINT(1) DEFAULT 0,
    college_honors_list TEXT,
    board_profession VARCHAR(255),
    board_exam_date VARCHAR(50),
    post_grad_course VARCHAR(255),
    post_grad_school VARCHAR(255),
    post_grad_date VARCHAR(50),
    post_grad_activity VARCHAR(100),
    activity_took_another_course VARCHAR(255),
    employee_work VARCHAR(255),
    employee_position VARCHAR(255),
    employee_years INT,
    trainings_seminars TEXT,
    interest_school_orgs TINYINT(1) DEFAULT 0,
    interest_religious TINYINT(1) DEFAULT 0,
    interest_sociocivic TINYINT(1) DEFAULT 0,
    interest_sports TINYINT(1) DEFAULT 0,
    interest_music_vocal TINYINT(1) DEFAULT 0,
    interest_dance TINYINT(1) DEFAULT 0,
    interest_creative_writing TINYINT(1) DEFAULT 0,
    interest_philately TINYINT(1) DEFAULT 0,
    interest_others VARCHAR(255),
    other_skills_work_exp TEXT,
    first_time_md_flag TINYINT(1) DEFAULT 1,
    prev_app_status VARCHAR(100),
    prev_med_school_name VARCHAR(255),
    motivation_parents TINYINT(1) DEFAULT 0,
    motivation_siblings TINYINT(1) DEFAULT 0,
    motivation_relatives TINYINT(1) DEFAULT 0,
    motivation_friends TINYINT(1) DEFAULT 0,
    motivation_illness TINYINT(1) DEFAULT 0,
    motivation_prestige TINYINT(1) DEFAULT 0,
    motivation_health_awareness TINYINT(1) DEFAULT 0,
    motivation_community_needs TINYINT(1) DEFAULT 0,
    motivation_others VARCHAR(255),
    future_plan VARCHAR(255),
    future_plan_other_postgrad VARCHAR(255),
    future_plan_others VARCHAR(255),
    support_parents TINYINT(1) DEFAULT 0,
    support_veteran_benefit TINYINT(1) DEFAULT 0,
    support_scholarship_flag TINYINT(1) DEFAULT 0,
    support_scholarship_name VARCHAR(255),
    support_others VARCHAR(255),
    support_status VARCHAR(100),
    info_parents TINYINT(1) DEFAULT 0,
    info_family_friends TINYINT(1) DEFAULT 0,
    info_student_friends TINYINT(1) DEFAULT 0,
    info_siblings TINYINT(1) DEFAULT 0,
    info_teachers TINYINT(1) DEFAULT 0,
    info_newspaper TINYINT(1) DEFAULT 0,
    info_convocation TINYINT(1) DEFAULT 0,
    info_internet TINYINT(1) DEFAULT 0,
    info_own_effort TINYINT(1) DEFAULT 0,
    info_others VARCHAR(255),
    staying_place VARCHAR(100),
    staying_place_others VARCHAR(255),
    pref_first_med_school VARCHAR(255),
    pref_second_med_school VARCHAR(255),
    pref_third_med_school VARCHAR(255),
    pref_other_med_schools TEXT,
    application_essay TEXT,
    
    -- STEP 5: Processing & Administration
    tor_path VARCHAR(255) NULL,
    photo_path VARCHAR(255) NULL,
    form137_path VARCHAR(255) NULL,
    birth_cert_path VARCHAR(255) NULL,
    nmat_path VARCHAR(255) NULL,
    diploma_path VARCHAR(255) NULL,
    gwa_cert_path VARCHAR(255) NULL,
    good_moral_path VARCHAR(255) NULL,
    other_docs_paths TEXT NULL,
    record_pdf_path VARCHAR(255) NULL,
    signed_document_path VARCHAR(255) NULL,
    passport_path VARCHAR(255) NULL,
    status ENUM('Pending', 'Accepted', 'Declined') DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
